### ISSUE TITLE
vcad

### ISSUE THREAD

**Issue by beyoneduk** [Miho931/vCAD-Tablet_Fivem-ESX#1]
how do i change the login to medicnet to english i have tried seaching each file for it i cant fine it and how do i login

**Comment by Miho931** [comment]
Hello, This is a tablet for our website.
You have to register at vcad.li.

For more information just join our Discord :)
https://discord.com/invite/fqXSMHH

**Comment by beyoneduk** [comment]
no have not register at vcad.li. but will now
